loro-dev/loro

crates/loro-wasm/src/lib.rs, loro-js/tests/basic.test.ts
This pull request adds three new methods to the `LoroMap` class: `keys()`, `values()`, and `entries()`. These methods allow for getting the keys, values, and entries of the map, respectively. The methods are implemented using the `for_each` method of the underlying `BTreeMap`. The `keys()` method returns an array of the keys of the map, the `values()` method returns an array of the values of the map, and the `entries()` method returns an array of arrays, where each sub-array contains a key-value pair of the map.
The pull request includes changes to the `LoroMap` class and to the tests for the `Loro` class.
=> Add map methods for getting keys, values, and entries

crates/loro-common/src/error.rs, crates/loro-internal/src/handler.rs, crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/basic.test.ts
This PR refactors the `get` methods in `ListHandler` and `MapHandler` to return a `ValueOrContainer` enum, which can hold either a `LoroValue` or a `Handler` to a container. This allows for easier handling of nested containers in the codebase.
feat: get sub container directly when getting value
Fixes #174
=> Refactor container value retrieval in handlers

crates/loro-wasm/scripts/build.ts
To fix #182 
On windows, `__filename` and `__dirname `  start with `/` in deno.
=> fix: deno dirname in windows

Cargo.lock, crates/loro-internal/Cargo.toml, crates/loro-internal/src/state/tree_state.rs
A compression flag has been removed from the encoding due to the update of `serde_columnar`.
=> BREAKING_CHANGE: Remove compress feature

crates/loro-internal/src/handler.rs, crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/basic.test.ts, loro-js/tests/misc.test.ts
- LoroMap.entries() now returns `Container` instead of `ContainerId` when the child is a container
- Replace `LoroList.value` with `LoroList.toArray()`
- Replace `*.getDeepValue()` with `*.toJson()`
- `LoroList.toArray()` returns `Container`  instead of `ContainerId` when the child is a container
- Add `kind()` function to all `Container`
- Add `valueType()` function and `isContainer()` function to get the type of the value quickly
It includes changes to the ListHandler and MapHandler classes, as well as updates to the for_each method to handle both values and containers. These changes make the code more maintainable and easier to understand.
=> (WASM )Refactor wasm interfaces on List and Map

Cargo.lock, crates/loro-internal/Cargo.toml, crates/loro-internal/fuzz/Cargo.toml, crates/loro-internal/src/encoding/encode_updates.rs, crates/loro-internal/src/version.rs, crates/loro-wasm/.cargo/config.toml, crates/loro-wasm/scripts/build.ts, crates/rle/Cargo.toml
Now WASM has 2.1MB. After compression,  `loro_wasm_bg.wasm.br` has 380KB
=> perf(wasm): reduce wasm size

crates/loro-internal/benches/encode.rs, crates/loro-internal/benches/pending.rs, crates/loro-internal/benches/tree.rs, crates/loro-internal/examples/automerge_x100.rs, crates/loro-internal/examples/pending.rs, crates/loro-internal/examples/tree.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/lib.rs, loro-js/tests/event.test.ts, loro-js/tests/richtext.test.ts
This pull request refactors the LoroDoc code to only require a shared reference in the loro doc now. 
This makes WASM faster and make `BorrowMutError` on `LoroDoc` in loro-wasm impossible.
=> Refactor LoroDoc shared reference

crates/loro-internal/Cargo.toml, crates/loro-internal/benches/event.rs, crates/loro-internal/examples/event.rs, crates/loro-internal/src/delta.rs, crates/loro-internal/src/delta/map_delta.rs, crates/loro-internal/src/event.rs, crates/loro-internal/src/fuzz.rs, crates/loro-internal/src/fuzz/recursive_refactored.rs, crates/loro-internal/src/fuzz/tree.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/src/value.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/event.test.ts, loro-js/vite.config.ts
return `ValueOrContainer` in diff event for a better developer experience.
@zxch3n I found that `vitest` sometimes times out and cannot exit. Do you know why? The main branch also has this problem.
=> Refactor: use ValueOrContainer for diff event

crates/loro-internal/fuzz/Cargo.lock, crates/loro-internal/src/container/richtext/tracker.rs, crates/loro-internal/src/container/richtext/tracker/crdt_rope.rs, crates/loro-internal/src/oplog.rs, loro-js/tests/issue.test.ts
fix #211
When applying a new op, it is necessary to slice it if the tracker already contains a partial segment of it.
=> fix: text tracker error #211

crates/loro-internal/src/container/richtext/tracker.rs, crates/loro-internal/src/diff_calc.rs, crates/loro-internal/tests/test.rs
This pull request fixes a bug in the `Tracker` implementation where partial inclusions were not handled correctly. The bug caused incorrect slicing of content and operations when the applied counter end was greater than the last ID's counter.
This fix ensures that partial inclusions are handled correctly in the `Tracker` implementation.
=> Fix partial inclusion bug in Tracker

Cargo.lock, crates/loro-common/Cargo.toml, crates/loro-common/src/internal_string.rs, crates/loro-common/src/lib.rs, crates/loro-internal/Cargo.toml, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state/map_state.rs
This pull request refactors the InternalString type to use the InternalString type from the loro-common crate. This change improves code consistency and removes the dependency on the string_cache crate.
=> Make InternalString a newtype

crates/loro-internal/src/container/richtext/tracker.rs, crates/loro-internal/src/fuzz/richtext.rs, crates/loro-internal/tests/test.rs
This pull request fixes an error in the tracker code where a delete operation was not being properly handled when the update was only partially included. The code has been updated to handle this scenario correctly.
=> Fix tracker delete error when the update is partially included

crates/loro-common/src/macros.rs, crates/loro-common/src/value.rs, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/state/tree_state.rs
This pull request updates the `loro_value!` macro to support binary data and adds new conversion implementations for `LoroValue` from `Vec<u8>`, `&[u8]`, and `[u8; N]`. This allows users to easily create `LoroValue` instances from binary data.
=> Update loro_value! macro and add binary support

crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/tracker.rs, crates/loro-internal/src/diff_calc.rs, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/fuzz/richtext.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/richtext_state.rs
This pull request fixes a time travel issue in the code. 
The issue was caused by the ambiguity of "reverse" in the `delete` method in `Tracker`. 
```rust
pub(crate) fn delete(&mut self, mut op_id: ID, pos: usize, mut len: usize, reverse: bool) {
...
}
```
When I wrote the buggy code, I thought `reverse` means it deleted elements in `pos-len+1..=pos`. But actually it means delete elements in `pos..pos+len` but the first op is the one that deletes element at `pos + len - 1`.
=> Fix time travel issue

Cargo.lock, crates/examples/Cargo.toml, crates/examples/examples/draw.rs, crates/examples/src/lib.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/style_range_map.rs, crates/loro-internal/src/delta/map_delta.rs, crates/loro-internal/src/diff_calc.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/tests/test.rs, crates/loro/src/lib.rs
This PR removes the abort behavior of transaction. So we no long need the undo stack in each container, which was used to revert the changes if the txn is aborted.
This PR also tries to reduce the mem usage by reducing the cost of storing states.
=> Remove txn abort and reduce mem usage

.vscode/settings.json, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/encode_reordered.rs
This pull request includes a performance improvement to refine the new encoding schema. It updates the encoding strategy for `peer_idx` field in the `EncodedChange` and `EncodedOp` struct. This leaves more room for further optimazation.
It also replace the derived `FromPrimitive` and `ToPrimitive` traits with manual impl for the `ValueKind` enum.
=> Refine the new encoding schema

crates/examples/examples/draw.rs, crates/loro-common/src/error.rs, crates/loro-internal/src/configure.rs, crates/loro-internal/src/container/richtext.rs, crates/loro-internal/src/container/richtext/config.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/style_range_map.rs, crates/loro-internal/src/delta/seq.rs, crates/loro-internal/src/delta/text.rs, crates/loro-internal/src/fuzz.rs, crates/loro-internal/src/fuzz/richtext.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/src/utils/lazy.rs, crates/loro-internal/src/value.rs, crates/loro-internal/tests/richtext.md, crates/loro-internal/tests/richtext.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/lib.rs, crates/loro/README.md, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/richtext.test.ts
This PR simplifies the usage of rich text.
We used to specify the expand behavior during each `mark` call. But it's quite hard to use, which makes introducing the types that allow overlapping harder. We only need to specify the configuration once at the doc level.
The usage before
```ts
const text = doc.getText("text");
text.insert(0, "foo");
text.mark({ start: 0, end: 3, expand: "none"}, "myStyle", 123);
expect(text.toDelta()).toStrictEqual([{ insert: 'foo', attributes: { myStyle: 123 } }]);
```
The usage now
```ts
// only need to do this once
doc.configTextStyle({
myStyle: {
expand: "none",
allowOverlap: false,
}
});
const text = doc.getText("text");
text.insert(0, "foo");
// don't need to specify the expand type now when we call `mark` …
```
=> refactor: use rich text style config

.vscode/settings.json, crates/loro-common/src/id.rs, crates/loro-common/src/lib.rs, crates/loro-internal/src/container.rs, crates/loro-wasm/src/lib.rs, examples/loro-quill/src/App.vue, examples/loro-quill/src/binding.ts, loro-js/tests/basic.test.ts, loro-js/tests/misc.test.ts, loro-js/tests/version.test.ts
Now, we use decimal as peer ID's string representation by default.
LORO-460
=> (wasm) Extract VersionVector class and fix inconsistent PeerID repr

crates/loro-common/src/value.rs, crates/loro-internal/src/container/richtext.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-wasm/CHANGELOG.md, crates/loro-wasm/package.json, loro-js/CHANGELOG.md, loro-js/package.json
Though counter-intuitive, when we toggle the `ExpandType` between for creation and for deletion, the correct conversion should be:
```
- ExpandType::After -> ExpandType::After
- ExpandType::Before -> ExpandType::Before
- ExpandType::None -> ExpandType::Both
- ExpandType::Both -> ExpandType::None
```
So that when there are overlaps between the style creation and the style's deletion, each style can still have the same expand type. For example:
When we make "Hello" bold and then make "ll" unbold if the style with `unbold` also has ExpandType::After, it'll make it appear to have a bold span at "He", and a bold span at "o", both have `ExpandType::After`, which is the desired behavior.
=> fix: how to find best insert pos for richtext & expand type reverse behavior

crates/loro-internal/src/container/richtext.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/style_range_map.rs, crates/loro-internal/src/delta/text.rs, crates/loro-internal/src/event.rs, crates/loro-internal/src/fuzz/richtext.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/src/value.rs, crates/loro/tests/loro_rust_test.rs
When traveling back, it should be able to nullify the newly created styles through the text event.
=> Fix rich text time travel event issue

Cargo.lock, crates/examples/Cargo.toml, crates/examples/examples/draw.rs, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/fuzz/recursive_refactored.rs, crates/loro-internal/src/state.rs
This PR involves a refactoring process where the `OpID` can be directly utilized as the `ID` portion of the `ContainerId` in child container creation operations. So we need not encode this kind of 'ContainerId', requiring only the 'ContainerType' to be encoded. The primary goal is to reduce document size.
The doc size of `draw` examples:
|    | main | | | | PR| | | |
|  ----  | ----  |---|---|---|----  |---|---|---|
| | snapshot| compressed snapshot|updates|compressed updates| snapshot| compressed snapshot|updates|compressed updates|
| async draw 100-1  | 3439 | 1664 | 2510 | 1281  | 3381 | 1499 | 2452 | 1115|
| async draw 10000-10  | 4289502 | 1537942 | 3149949 | 1168121 |3950650 | 1242185 | 2811097 | 889327 | 
| realtime draw 100-5  | 2242 | 1278 | 1690 | 1009 |2212 | 1189 | 1660 | 918| …
=> refactor: Optimizing Encoding Representation for Child Container Creation to Reduce Document Size

crates/loro/src/lib.rs
I think this was just forgotten since the getter is exported in loro-wasm
=> add PeerID Getter to public API of loro crate

crates/examples/src/draw.rs, crates/loro-common/src/macros.rs, crates/loro-common/src/value.rs, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/fuzz.rs, crates/loro-internal/src/fuzz/recursive_refactored.rs, crates/loro-internal/src/fuzz/richtext.rs, crates/loro-internal/src/fuzz/tree.rs, crates/loro-wasm/src/convert.rs, crates/rle/src/rle_vec.rs
They have the same cost in terms of mem and storage and i64 will be more useful. For compatibility, JS number also supports up to 53-bit integer. So there is no reason for us to stick with i32.
=> refactor: replace LoroValue::i32 with i64

crates/loro-common/src/error.rs, crates/loro-internal/src/change.rs, crates/loro-internal/src/configure.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/basic.test.ts
- Timestamp will not be recorded by default. It will use 0 as the default value instead
- Users can now control the mergeable interval
- Use standard Unix Timestamp as the timestamp
Enable Timestamp.
```ts
doc.setPeerId(1);
doc.getText("123").insert(0, "123");
doc.commit();
{
const c = doc.getChangeAt({ peer: "1", counter: 0 });
expect(c.timestamp).toBe(0);
}
doc.setRecordTimestamp(true);
doc.getText("123").insert(0, "123");
doc.commit();
{
const c = doc.getChangeAt({ peer: "1", counter: 4 });
expect(c.timestamp).toBeCloseTo(Date.now(), 0);
}
```
Commit with a specific timestamp:
```ts
doc.setPeerId(1);
doc.getText("123").insert(0, "123");
doc.commit(undefined, 111);
const c = doc.getChangeAt({ peer: "1", counter: 0 }); …
```
=> feat: expose timestamp related configures

crates/loro-internal/src/loro.rs, crates/loro-internal/tests/test.rs
If any function that needs the lock of `state` is called in `Subscriber`, the deadlock will happen.
=> fix: state lock when emit events

crates/loro-internal/src/arena.rs, crates/loro-internal/src/diff_calc.rs, crates/loro-internal/tests/test.rs
When the doc is attached, it uses the `diff_calc` in `LoroDoc`, and the depth of `ContainerDiffCalculator` may still be the old cached value. That causes the `diff_calc` to believe that the depth is inconsistent and the container may have been deleted. So we cannot receive the event.
Maybe we should have a better way to determine whether the container is deleted.
=> fix missing event when checkout

crates/loro-common/src/lib.rs, crates/loro-internal/src/handler.rs, crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/basic.test.ts
```ts
const docA = new Loro();
const map = docA.getMap("map");
const container = map.getOrCreateContainer("list", "List");
container.insert(0, 1);
container.insert(0, 2);
const text = map.getOrCreateContainer("text", "Text");
text.insert(0, "Hello");
expect(docA.toJson()).toStrictEqual({
map: { list: [2, 1], text: "Hello" },
});
```
=> feat: add getOrCreateContainer for Map

crates/loro-internal/src/handler.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, loro-js/tests/basic.test.ts
```
const m = doc.getMap("m");
expect(m.parent()).toBeUndefined();
const list = m.setContainer("t", "List");
expect(list.parent()!.id).toBe(m.id);
const text = list.insertContainer(0, "Text");
expect(text.parent()!.id).toBe(list.id);
const tree = list.insertContainer(1, "Tree");
expect(tree.parent()!.id).toBe(list.id);
const treeNode = tree.createNode();
const subtext = treeNode.data.setContainer("t", "Text");
expect(subtext.parent()!.id).toBe(treeNode.data.id);
```
=> feat: add getParent for each handler

crates/loro-wasm/src/lib.rs, loro-js/package.json, loro-js/src/index.ts, loro-js/tests/basic.test.ts, loro-js/tests/type.test.ts
Now, the type system can tell you whether a container is attached statically.
```ts
test("Container attached state", () => {
const list = new LoroList();
expect(list.isAttached()).toBe(false);
expectTypeOf(list.isAttached()).toMatchTypeOf<false>();
{
const map = doc.getMap("map");
expectTypeOf(map.isAttached()).toMatchTypeOf<true>();
expectTypeOf(map).toMatchTypeOf<LoroMap<any, true>>();
}
{
const map = new LoroMap();
expectTypeOf(map.isAttached()).toMatchTypeOf<false>();
expectTypeOf(map).toMatchTypeOf<LoroMap<any, false>>();
}
{
const map = list.insertContainer(0, new LoroMap());
expectTypeOf(map.isAttached()).toMatchTypeOf<false>();
expectTypeOf(map).toMatchTypeOf<LoroMap<any, false>>();
}
});
```
=> fix: type mismatch and add type info for whether a container is attached

crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/type.test.ts
The type on `isAttached` is removed; it was able to infer the true/false correctly. Because it would cause downstream marking types harder.
TypeScript doesn't support type annotation on the constructor yet https://github.com/microsoft/TypeScript/issues/27594  Otherwise, we may have a perfect solution.
=> refactor: rm isAttached type on containers

crates/loro-internal/scripts/fuzz.ts, crates/loro-internal/src/event.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/scripts/build.ts, crates/loro-wasm/src/lib.rs, crates/loro/src/event.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, examples/loro-quill/src/binding.ts, loro-js/src/index.ts, loro-js/tests/checkout.test.ts, loro-js/tests/event.test.ts, loro-js/tests/issue.test.ts, loro-js/tests/misc.test.ts, loro-js/tests/richtext.test.ts, loro-js/tests/version.test.ts
Downstream apps need to know how an event is triggered. There are 3 kinds of cases currently:
- Triggered by a local transaction
- Triggered by an import 
- Triggered by checkout to another version
The old design represents them with two booleans in the `Event` type:
- `local`
- `fromCheckout`
However, whether a checkout should be `local` is unclear, creating confusion for the downstream apps. It also creates room for an invalid state because two booleans have four variants. 
This PR introduces a breaking change that replaces the two fields with one `by: 'local'|'import'|'checkout'`.
=> refactor: replace "local" and "fromCheckout" in event with "triggeredBy"

crates/loro-wasm/src/lib.rs, loro-js/package.json, loro-js/tests/issue.test.ts, loro-js/tests/type.test.ts, loro-js/tsconfig.json
Now we can use `.kind()` to infer the type:
```ts
function foo(c: Container) {
if (c.kind() === "Text"){
// TypeScript now knows it's a `LoroText` container
...
}
}
```
=> refactor: add concrete type for each different container

crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/misc.test.ts, loro-js/tests/type.test.ts
The APIs like `.getTyped()` `getTypedMap()`... are removed. 
Now the following code is valid 
```ts
const t = doc.getText("t");
expectTypeOf(getType(t)).toEqualTypeOf<"Text">();
expect(getType(t)).toBe("Text");
expectTypeOf(getType(123)).toEqualTypeOf<"Json">();
expect(getType(123)).toBe("Json");
expectTypeOf(getType(undefined)).toEqualTypeOf<"Json">();
expect(getType(undefined)).toBe("Json");
expectTypeOf(getType(null)).toEqualTypeOf<"Json">();
expect(getType(null)).toBe("Json");
expectTypeOf(getType({})).toEqualTypeOf<"Json">();
expect(getType({})).toBe("Json");
const map = doc.getMap("map");
const list = doc.getList("list");
const tree = doc.getTree("tree");
const text = doc.getText("text");
expectTypeOf(getType(map)).toEqualTypeOf<"Map">(); …
```
=> refactor(ts): make method types better

crates/bench-utils/Cargo.toml, crates/delta/Cargo.toml, crates/loro-wasm/Cargo.toml, crates/loro/Cargo.toml
to allow Crates.io, lib.rs and the rust-digger to link to it
=> add repository field

.github/workflows/release_wasm.yml, .github/workflows/rust.yml, CONTRIBUTING.md, Cargo.lock, crates/loro-common/Cargo.toml, crates/loro-internal/Cargo.toml, crates/loro-wasm/Cargo.toml, loro-js/tests/richtext.test.ts
This is a bug triggered by wasm-bindgen. It's fixed already https://github.com/rustwasm/wasm-bindgen/pull/3808.
The bevaior is when you insert `'“aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'` to a LoroText in JS, it panics with the following error message:
```
005573b2:0x1426a5 panicked at /rust/deps/dlmalloc-0.2.6/src/dlmalloc.rs:1198:13:
assertion failed: psize <= size + max_overhead
Stack:
Error
at __wbg_new_abda76e883ba8a5f (https://local.kymyth.com:5173/node_modules/.vite/deps/loro-crdt.js?v=e1fe92cd:4264:15)
at wasm://wasm/005573b2:wasm-function[2447]:0x142628
at wasm://wasm/005573b2:wasm-function[842]:0xe17f0
at wasm://wasm/005573b2:wasm-function[1916]:0x13738f
at wasm://wasm/005573b2:wasm-function[1854]:0x135167
at wasm://wasm/005573b2:wasm-function[2303]:0x13fb40
at …
```
=> fix: upgrade wasm-bindgen to fix str free err

.github/workflows/release_wasm.yml, loro-js/src/index.ts, loro-js/tests/basic.test.ts, pnpm-lock.yaml
Fixes `isContainer` for MovableList
Right now, `isContainer` returns false when called with a `MovableList`
```ts
import { isContainer, Loro } from "loro-crdt";
const loro = new Loro();
isContainer(loro.getMovableList("foo")); // false (should be true)
```
=> fix: add MovableList to CONTAINER_TYPES

.changeset/sharp-rules-report.md, crates/loro-internal/src/undo.rs, crates/loro-wasm/deno.lock
This change internalizes some logic related to cursor transformation when performing undo/redo. It makes the API much simpler.
Specifically, the recorded cursor info for each undo/redo item is different when we're inside an undo/redo loop.
```log
// When in the undo/redo loop, the new undo/redo stack item should restore the selection
// to the state it was in before the item that was popped two steps ago from the stack.
//
//                          ┌────────────┐
//                          │Selection 1 │
//                          └─────┬──────┘
//                                │   Some
//                                ▼   ops
//                          ┌────────────┐
//                          │Selection 2 │
//                          └─────┬──────┘
// …
```
=> Refactor undo cursor

crates/loro/Cargo.toml, crates/loro/src/lib.rs
=> fix: workaround lldb bug make loro crate debuggable

crates/fuzz/src/crdt_fuzzer.rs, crates/fuzz/tests/test.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/undo.rs
When performing undo and redo operations for a tree node deletion, a new `TreeID` is used due to the associated Data MapContainer. 
However, concurrent operations might bring back the deleted node while keeping its original `TreeID`. This results in the node having two IDs in the undo manager: the original and the newly created one from the redo. 
To address this, we need to remove the bring-back node from the remapping when importing.
=> fix: delete the **bring back** tree node from the undo container remap 

Cargo.lock, crates/fuzz/Cargo.toml, crates/fuzz/tests/compatibility.rs, crates/loro-internal/src/change.rs, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/encoding/json_schema.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro-internal/src/oplog/change_store/block_encode.rs, crates/loro-internal/src/txn.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/change_meta.rs, crates/loro/src/lib.rs, crates/loro/tests/commit_message_test.rs
Support adding a commit message for each `Change`. 
```rust
let doc = LoroDoc::new();
let text = doc.get_text("text");
text.insert(0, "hello").unwrap();
doc.commit_with(CommitOptions::new().commit_msg("edits"));
let change = doc.get_change(ID::new(doc.peer_id(), 0)).unwrap();
assert_eq!(change.message(), "edits");
// The commit message can be synced to other peers as well
let doc2 = LoroDoc::new();
doc2.import(&doc.export_snapshot()).unwrap();
let change = doc.get_change(ID::new(doc.peer_id(), 1)).unwrap();
assert_eq!(change.message(), "edits");
```
=> feat: support commit message

.vscode/settings.json, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/fast_snapshot.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/obs.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/src/utils/mod.rs, crates/loro-internal/src/utils/subscription.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/event.test.ts
This PR introduces a new method `subscribeLocalUpdates` to the Loro API, enabling users to listen for local changes made to the document.
This allows users to subscribe to doc's local updates without the manual `exportFrom(lastVV)`, which might also include the recent imported changes and make the system less efficient.
- Subscribe to local updates in Loro instances
- Receive updates as `Uint8Array`
- Unsubscribe functionality included
1. Syncing changes between multiple Loro instances
2. Saving updates to a persistent storage
3. Implementing custom change tracking or logging
```typescript
const loro = new Loro();
const unsubscribe = loro.subscribeLocalUpdates((update) => {
console.log("Local update received:", update);
// Handle the update (e.g., send to other instances, save to storage) …
```
=> Feat subscribe local updates

crates/loro-internal/src/change.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/change_meta.rs
It's much more efficient than using milliseconds in Loro's use cases
=> Record timestamp in seconds by default

crates/fuzz/src/actor.rs, crates/fuzz/src/container/tree.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/handler/tree.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, loro-js/src/index.ts, loro-js/tests/tree.test.ts
- `contains()`/`has()`:  Deleted nodes are also included. Returns `false` only if the node does not exist.
- `nodes()`: Deleted nodes are also included.
- `isNodeDeleted()`: Added a function to determine whether a node is deleted.
=> refactor: tree contains & isDeleted

crates/fuzz/src/actor.rs, crates/fuzz/src/container/tree.rs, crates/fuzz/tests/compatibility.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/handler/tree.rs, crates/loro-internal/src/history_cache.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/tree.test.ts
- add `getNodes({withDeleted: boolean})` for getting all `LoroTreeNode`s, if `withDeleted` is true, deleted nodes will also be included.
`get_value()`/`get_deep_value()`: use hierarchy instead of flat data
=> refactor: use hierarchy value for tree value

crates/loro-common/src/error.rs, crates/loro-common/src/lib.rs, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/fast_snapshot.rs, crates/loro-internal/src/encoding/gc.rs, crates/loro-internal/src/fork.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro-internal/src/version.rs, crates/loro/src/lib.rs, crates/loro/tests/integration_test/mod.rs, crates/loro/tests/integration_test/snapshot_at_test.rs, crates/loro/tests/loro_rust_test.rs
This PR introduces the fork_at feature to the LoroDoc system, enabling the creation of a new document instance that reflects the state of the original document at a specified version (Frontiers). It serves as a primitive for building higher-level version control systems.
=> feat: add fork_at functionality to create a document at a target version

crates/fuzz/src/actor.rs, crates/fuzz/tests/test.rs, crates/loro-internal/src/encoding/gc.rs, crates/loro-internal/src/state/container_store.rs, crates/loro-internal/src/state/container_store/inner_store.rs
it should retain all containers created after the `from` version
=> fix: gc snapshot error

crates/loro-internal/src/encoding/json_schema.rs, crates/loro-internal/src/version.rs, crates/loro/tests/integration_test/mod.rs, crates/loro/tests/integration_test/redact_test.rs
=> feat: redact

crates/loro-wasm/src/lib.rs, loro-js/package.json, loro-js/tests/event.test.ts
=> fix: subscription convert error

.changeset/hip-squids-train.md, Cargo.lock, crates/loro-internal/src/loro.rs, crates/loro-internal/src/op.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/Cargo.toml, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
Added a new API `getChangedContainersIn()` that allows users to query which containers were modified within a specific range of changes in the document's history. This feature enables better analysis and tracking of document modifications across containers.
- Added `getChangedContainersIn(id, len)` method to `LoroDoc` that returns a set of container IDs modified in the given range
- Implemented in Rust core with `FxHashSet` for efficient unique container tracking
- Exposed through WASM bindings for JavaScript/TypeScript usage
- Added comprehensive tests in both Rust and TypeScript
```ts
const doc = new LoroDoc();
doc.setPeerId("0");
doc.getText("text").insert(0, "H");
doc.getMap("map").set("key", "H");
const changed = doc.getChangedContainersIn({ peer: "0", counter: 0 }, 2)
const …
```
=> feat: allow users to query the changed containers in the target id range

Cargo.lock, crates/examples/examples/large_map.rs, crates/examples/examples/sheet.rs, crates/loro-common/Cargo.toml, crates/loro-common/src/internal_string.rs, crates/loro-internal/src/delta/map.rs, crates/loro/src/lib.rs
In the old implementation of InternalString, performance would degrade significantly when dealing with a large number of different InternalStrings.
In the following example
```rust
use std::time::Instant;
use dev_utils::get_mem_usage;
use loro::LoroDoc;
fn main() {
let mut init = Instant::now();
{
let start = Instant::now();
let doc = LoroDoc::new();
let map = doc.get_map("map");
for i in 0..1000 {
for j in 0..1000 {
let key = format!("0000{}:0000{}", i, j);
map.insert(&key, i + j).unwrap();
}
}
println!("LargeMap Init Time {:?}", start.elapsed());
let start = Instant::now();
let bytes = doc.export(loro::ExportMode::Snapshot).unwrap();
println!("LargeMap Export Time {:?}", start.elapsed());
let start = Instant::now();
let new_doc = LoroDoc::new();
new_doc.import(&bytes).unwrap(); …
```
=> perf: use simplified internal string

.changeset/soft-goats-peel.md, crates/loro-internal/src/state/tree_state.rs, crates/loro-wasm/deno_tests/basic.test.ts, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/counter.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
This PR adds the ability to check if a container has been deleted through the new `isDeleted()` method available on all container types.
- Added `isDeleted()` method to the `ContainerTrait` trait
- Implemented `isDeleted()` for all container types:
- LoroText
- LoroMap 
- LoroList
- LoroTree
- LoroMovableList
- LoroCounter
- LoroUnknown
- Fixed tracking of deleted containers in tree operations
- Added comprehensive tests covering various deletion scenarios:
- Tree node deletion
- Movable list container replacement
- Map value overwrite
- Remote deletion sync
Added test cases to verify deletion status:
- Basic container deletion through tree operations
- Container replacement in movable lists
- Map value overwriting
- Cross-document deletion sync
```typescript
const doc = new LoroDoc(); …
```
=> feat: Add isDeleted() method to containers

.changeset/popular-spoons-wash.md, crates/examples/examples/large_map.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/handler/tree.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/tests/tree.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/__snapshots__/tree.test.ts.snap, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
Otherwise, there may be inconsistency between the tree event and the actual data because the `index` info in the event may be wrong. If the `index` property is unused, users can still disable the use of fractional index by `tree.disableFractionalIndex()`.
=> fix: tree should use jitter 0 by default

crates/loro-wasm/index.ts, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/json.test.ts
Add a new method for customizing the behavior of `toJSON` for JS.
```ts
/**
* Convert the document to a JSON value with a custom replacer function.
* 
* This method works similarly to `JSON.stringify`'s replacer parameter.
* The replacer function is called for each value in the document and can transform
* how values are serialized to JSON.
* 
* @param replacer - A function that takes a key and value, and returns how that value
*                  should be serialized. Similar to JSON.stringify's replacer. 
*                  If return undefined, the value will be skipped.
* @returns The JSON representation of the document after applying the replacer function.
* 
* @example
* ```ts
* const doc = new LoroDoc();
* const text = doc.getText("text");
* text.insert(0, "Hello");
* text.mark(0, 2, …
=> feat: implement toJsonWithReplacer method for LoroDoc to customize JSON serialization

.changeset/violet-fishes-smile.md, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts
If the method takes ownership of the VersionVector in WASM binding, the VersionVector will be freed. So it can no longer be used in JS.
=> fix(wasm): ownership of vv

.changeset/tricky-bees-peel.md, crates/loro-internal/src/state.rs, crates/loro/tests/loro_rust_test.rs
The event will now be ordered by (depth, container counter). Therefore, two container creation events within the same layer will be sorted based on the containers’ counter values. This approach can prevent the issue where child tree node events are received before the parent tree node events
=> Fix-better-event-order

crates/loro-wasm/src/lib.rs
- removed unused move() and parent() docs
`loro_wasm.d.ts` difference:
```diff
diff --git a/crates/loro-wasm/loro_wasm-before.d.ts b/crates/loro-wasm/nodejs/loro_wasm.d.ts
index 14dacdef..575d7a18 100644
--- a/crates/loro-wasm/loro_wasm-before.d.ts
+++ b/crates/loro-wasm/nodejs/loro_wasm.d.ts
@@ -397,11 +397,6 @@ export type TreeNodeJSON<T> = Omit<TreeNodeValue, 'meta' | 'children'> & {
children: TreeNodeJSON<T>[],
}
-interface LoroTree{
-    toArray(): TreeNodeValue[];
-    getNodes(options?: { withDeleted?: boolean } ): LoroTreeNode[];
-}
-
interface LoroMovableList {
/**
* Get the cursor position at the given pos.
@@ -1129,6 +1124,8 @@ interface LoroTree<T extends Record<string, unknown> = Record<string, unknown>>
*/
getNodeByID(target: TreeID): LoroTreeNode<T>;
subscribe(listener: …
```
=> fix(typescript): tree node parent() + move() use generics

.changeset/popular-ghosts-travel.md, crates/loro-internal/benches/encode.rs, crates/loro-internal/examples/encoding.rs, crates/loro-internal/examples/encoding_refactored.rs, crates/loro-internal/src/encoding/json_schema.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog/change_store/block_encode.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs, crates/loro/tests/integration_test/detached_editing_test.rs, crates/loro/tests/loro_rust_test.rs
This change will make the internal operations more accessible to the application code.
- Introduced `export_json_updates_without_peer_compression` method to allow exporting JSON updates without compressing peer IDs, making it easier for application code to process.
- Updated existing `export_json_updates` method to accept a `with_peer_compression` parameter, defaulting to true.
- Refactored related code in various files to accommodate the new functionality, ensuring backward compatibility.
=> feat: add exportJsonInIdSpan and make peer compression optional

.changeset/tame-spies-attack.md, crates/loro-ffi/src/version.rs, crates/loro-internal/src/dag.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/version.rs, crates/loro-wasm/deno_tests/basic.test.ts, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, scripts/deno.lock, scripts/run-js-doc-tests.ts
Now you can now inspect all the changes that happened in an event:
```ts
const docA = new LoroDoc();
docA.setPeerId("1");
const docB = new LoroDoc();
docA.getText("text").update("Hello");
docA.commit();
const snapshot = docA.export({ mode: "snapshot" });
let done = false;
docB.subscribe(e => {
const spans = docB.findIdSpansBetween(e.from, e.to);
expect(spans.retreat).toHaveLength(0);
expect(spans.forward).toHaveLength(1);
expect(spans.forward[0]).toEqual({
peer: "1",
counter: 0,
length: 5,
});
const changes = docB.exportJsonInIdSpan(spans.forward[0]);
expect(changes).toStrictEqual([{
id: "0@1",
timestamp: expect.any(Number),
deps: [],
lamport: 0,
msg: undefined,
ops: [{
container: "cid:root-text:Text",
counter: 0,
content: {
type: "insert",
pos: 0,
text: "Hello"
}
}]
}]);
done = true;
}); …
```
=> feat: find id spans between

crates/loro-ffi/src/container/text.rs, crates/loro-ffi/src/event.rs
This is my first time working with rust so I apologize if this isn't the right direction, but I think we need this to be able to define apply_delta in the swift udl.
=> Adjust the ffi for apply_delta to map between ffi TextDelta and internal TextDelta

.changeset/rude-candles-jog.md, crates/loro-internal/src/change.rs, crates/loro-internal/src/configure.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro-internal/src/undo.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
`setChangeMergeInterval` should only be used to merge the local changes that are not committed yet.
=> fix: prevent merging remote changes based on local `changeMergeInterval` config

crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/counter.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts
=> fix: LoroCounter issues #626

crates/fuzz/src/actor.rs, crates/loro-ffi/src/undo.rs, crates/loro-internal/src/delta/map_delta.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/handler/tree.rs, crates/loro-internal/src/jsonpath.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/counter_state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/movable_list_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/src/state/unknown_state.rs, crates/loro-internal/src/subscription.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/src/undo.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/counter.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/counter.rs, crates/loro/src/lib.rs, crates/loro/tests/integration_test/detached_editing_test.rs, crates/loro/tests/integration_test/undo_test.rs
Each `Container` needs to hold a reference to `LoroDoc` to prevent scenarios like https://github.com/loro-dev/loro-py/pull/7 where `LoroDoc` might be dropped while the `Container`'s methods are being called.
=> refactor:  hold doc reference in handler

.changeset/tasty-dodos-repeat.md, crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro/tests/loro_rust_test.rs
This pull request includes several changes to the `crates/loro-internal` and `crates/loro/tests` directories to improve the handling of version vectors, error checking, and testing. The most important changes are summarized below:
* [`crates/loro-internal/src/loro.rs`](diffhunk://#diff-013c660b26d7d75e7041e30dc5320b06b668c5bf375c10120d37f4518ffba5feR573-R593): Added logic in `export_json_updates` to ensure `start_vv` is greater than or equal to `shallow_since_vv` by extending `start_vv` if necessary.
* [`crates/loro-internal/src/oplog/change_store.rs`](diffhunk://#diff-3c45ed5ba5f90a51ffe47156f5a3a8358457831fb664c110c50d0df070549078L300-R311): Added checks to return an empty vector if `next_back` is `None` or if the peer ID does not match `id_span.peer`.
* …
=> fix: improve shallow snapshot and JSON export handling

crates/loro-internal/src/state.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/tests/loro_rust_test.rs
resolve: get_by_str_path for trees doesn't return the node meta at the index #625
=> fix: getting values by path in LoroTree

.changeset/curvy-pens-film.md, crates/loro-internal/src/jsonpath.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/undo.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs
This change introduces a new `has_container` method to check if a container exists in a document. The method is added to both the Rust internal implementation and the WASM bindings.
Key changes:
- Modify `get_handler` to return an `Option<Handler>` instead of panicking
- Add `has_container` method to check container existence
=> feat: add container existence check methods & avoid panic in wasm/js

.changeset/late-gifts-jog.md, crates/loro-internal/src/change.rs, crates/loro-internal/src/encoding/json_schema.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/txn.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts
resolve #664
```ts
const doc = new LoroDoc();
doc.setPeerId("1");
expect(doc.getUncommittedOpsAsJson()).toBeUndefined();
const text = doc.getText("text");
text.insert(0, "Hello");
const pendingOps = doc.getUncommittedOpsAsJson()
expect(pendingOps).toBeDefined();
expect(JSON.stringify(pendingOps)).toContain("insert");
expect(JSON.stringify(pendingOps)).toContain("Hello");
expect(pendingOps).toEqual({
"peers": undefined,
"schema_version": 1,
"start_version": {},
changes: [{
"id": "0@1",
"deps": [],
"msg": undefined,
"lamport": 0,
"ops": [
{
"container": "cid:root-text:Text",
"counter": 0,
"content": {
"type": "insert",
"pos": 0,
"text": "Hello"
}
}
],
"timestamp": 0,
}],
})
```
=> feat: get pending ops from current txn as json

crates/loro-internal/Cargo.toml
Running
```bash 
cd crates/loro && cargo build --target wasm32-unknown-unknown
```
Gives the following:
```bash
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
--> /Users/synoet/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.15/src/lib.rs:342:9
|
342 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
343 | |                         default, you may need to enable the \"js\" feature. \
344 | |                         For more information see: \
345 | |                         https://docs.rs/getrandom/#webassembly-support");
| |________________________________________________________________________^ …
```
=> fix: --target wasm32-unknown-unknown for loro crate (getrandom dep)

crates/loro-internal/Cargo.toml, crates/loro-internal/src/change.rs
`get_sys_timestamp` only properly uses browser time api, if the `wasm` feature flag is enabled. But enabling the `wasm` feature flag pins the `wasm-bindgen` version (assuming because `loro-wasm` crate depends on this specific version), which prevents using `loro-internal` with runtimes that require a higher `wasm-bindgen` version. But when compiling to `wasm32-unknown-unknown` I don't think the pinned restriction is required, and we can keep the browser `get_sys_timestamp` implementation without requiring the `wasm` feature.
=> fix(loro-internal): support get_sys_timestamp wasm32 without wasm feature

.changeset/old-bananas-appear.md, .github/workflows/rust.yml, CONTRIBUTING.md, Cargo.lock, crates/loro-common/Cargo.toml, crates/loro-internal/Cargo.toml, crates/loro-wasm/Cargo.toml, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/counter.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/mem.test.ts
wasm-bindgen had a memory leak issue (https://github.com/rustwasm/wasm-bindgen/issues/3854). It causes the document initialized by `new LoroDoc()` to not be garbage collected correctly.
=> fix: upgrade wasm-bindgen to fix mem leak

.changeset/chilled-pugs-beam.md, crates/loro-ffi/src/ephemeral.rs, crates/loro-internal/src/awareness.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/awareness.rs, crates/loro-wasm/tests/ephemeral.test.ts
=> fix: add mutex to ephemeral store

crates/loro-ffi/src/undo.rs, crates/loro-internal/src/undo.rs, crates/loro/src/lib.rs, crates/loro/tests/integration_test/undo_test.rs
Changes:
- Surface the `undo_stack` and `redo_stack` depths
- Add `undo_count()` and `redo_count()` checks to unit tests
This helps us use Loro's UndoManager as an alternative implementation of Cocoa Foundation's [UndoManager](https://developer.apple.com/documentation/foundation/undomanager/) API, which is obliged to be able to return an `undoCount` and `redoCount`.
=> Add UndoManager `undo_count()` and `redo_count()`

.changeset/strange-onions-eat.md, crates/loro-wasm/src/lib.rs
Need to serialize op with bigint support otherwhise might run into something like this.
``` 00c11f2e:0x20b225 panicked at crates/loro-wasm/src/lib.rs:1804:56:
called Result::unwrap() on an Err value: Error(JsValue(Error: 5476599770687706205 can't be represented as a JavaScript number ```
=> fix(wasm): serialize op with bigint support

crates/kv-store/Cargo.toml
This PR is intended to fix #760.
I also created a PR to the ahash project upstream, which would pass the wasm_js feature flag to getrandom when building the wasm32-unknown-unknown target. The ahash project does appear to be actively maintained. However, it looks like on average, their releases are a few months apart, and I don't know for sure that the PR will be accepted by the maintainers there.
Thus, in the meantime, I am also proposing a fix that's entirely self-contained within the Loro project. The quick_cache crates includes ahash as a default feature, but it's not actually required for successful operation of the crate. If default features are disabled, quick_cache reverts back to using a different hash mechanism that doesn't trigger the getrandom build error. The PR modifies the …
=> Omit ahash dependency for wasm32-unknown-unknown builds
