crates/loro-wasm/src/lib.rs
=> fix: typo in lib.rs

crates/loro-wasm/src/lib.rs, loro-js/tests/basic.test.ts
=> Fix: Keep strong reference to doc in handlers

crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/style_range_map.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/tests/test.rs
=> fix: Ignore redundant marks

crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/delta/text.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/tests/test.rs, crates/loro/README.md, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/richtext.test.ts
The attributes in delta's insertions should override the inherited attr
Fixes #225
=> Fix issue with richtext's applyDelta() behavior

crates/loro-internal/src/handler.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/tests/autocommit.rs, crates/loro-internal/tests/richtext.rs
This pull request refactors the container states to include container IDs and adds consistency checks for the state calculations.
=> Refactor container states and add consistency checks

crates/loro-internal/src/loro.rs, crates/loro-internal/tests/test.rs
The doc may be in a transaction.
=> fix: should not reset the state when calling checkout to latest

crates/loro-internal/src/container/richtext/tracker.rs
=> fix: tracker insert err

crates/loro-common/src/error.rs, crates/loro-common/src/lib.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/container/richtext/tracker/crdt_rope.rs, crates/loro-internal/src/op.rs, crates/loro-internal/src/state/list_state.rs
This pull request includes a fix for a few legacy bugs
=> Fix legacy bugs

crates/loro-common/src/value.rs, crates/loro-internal/src/fuzz.rs, crates/loro-internal/src/fuzz/recursive_refactored.rs, crates/loro-internal/src/fuzz/tree.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/obs.rs, crates/loro-internal/src/txn.rs, crates/loro-internal/tests/autocommit.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs
This pull request includes a refactoring of the handler modules to extract common methods. 
Co-Authored-By: Leon <leeeon233@gmail.com>
=> refactor: extract common methods on handlers

crates/loro-wasm/src/convert.rs
We relied on constructors' names to infer the correct container type in Rust. However, this way is not reliable
=> fix: avoid bundlers change the classname to cause converting a js container value back to rust

crates/loro-wasm/src/lib.rs, loro-js/src/index.ts, loro-js/tests/type.test.ts
=> docs: clarify that peer id should be convertible to a u64

crates/loro-common/src/lib.rs, crates/loro-internal/src/arena.rs, crates/loro-internal/src/event.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/basic.test.ts
=> feat: access value/container by path

crates/fuzz/fuzz/Cargo.lock, crates/loro-internal/fuzz/Cargo.lock, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/encode_reordered.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/version.rs, crates/loro-wasm/src/convert.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs, loro-js/tests/version.test.ts
=> feat: decode import blob meta

loro-js/package.json, loro-js/tests/compatibility.test.ts, pnpm-lock.yaml
Add basic forward compatibility & backward compatibility check
=> test: add compatibility tests

crates/loro-common/src/error.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/tests/test.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, loro-js/tests/richtext.test.ts
=> feat: add insert_utf8 and delete_utf8 for Rust Text API

crates/loro-internal/src/loro.rs, crates/loro-internal/src/oplog/change_store.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/container_store.rs, crates/loro-internal/src/state/container_store/container_wrapper.rs, crates/loro-internal/src/state/container_store/inner_store.rs, crates/loro-internal/src/state/counter_state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/movable_list_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/src/state/unknown_state.rs, crates/loro/tests/loro_rust_test.rs
=> fix: fork error

crates/bench-utils/src/json.rs, crates/fuzz/tests/compatibility.rs, crates/loro-common/src/lib.rs, crates/loro-common/src/macros.rs, crates/loro-common/src/value.rs, crates/loro-ffi/src/value.rs, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/delta/text.rs, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/outdated_encode_reordered.rs, crates/loro-internal/src/encoding/value.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/lib.rs, crates/loro-internal/src/state.rs, crates/loro-internal/src/state/list_state.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/movable_list_state.rs, crates/loro-internal/src/state/richtext_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-internal/src/value.rs, crates/loro-wasm/src/convert.rs, crates/loro/src/lib.rs
- **refactor: extract LoroStringValue LoroMapValue LoroListValue LoroBinaryValue**
- **chore: clippy fix**
- **chore: fix warning**
=> refactor(rust): extract LoroStringValue, LoroMapValue, LoroBinaryValue, LoroListValue

.changeset/hip-pears-accept.md, crates/loro-internal/src/handler.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs
- **feat: add push_container and push_str to list/text**
- **chore: add changeset file**
=> feat: add push/push_container to LoroText/LoroList/LoroMovableList

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Loro Guru](https://gurubase.io/g/loro) to Gurubase. Loro Guru uses the data from this repo and data from the [docs](https://loro.dev/docs) to answer questions by leveraging the LLM.
In this PR, I showcased the "Loro Guru", which highlights that Loro now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Loro …
=> Introducing Loro Guru on Gurubase.io

.changeset/funny-cats-divide.md, .changeset/hot-comics-type.md, crates/loro-common/src/lib.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/handler/tree.rs, crates/loro-internal/src/state/map_state.rs, crates/loro-internal/src/state/movable_list_state.rs, crates/loro-internal/src/state/tree_state.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
- **feat: LoroMap::get_last_editor**
- **feat: get creator/mover/editor of items**
- **chore: add changeset**
=> Feat add API to query creators, the last editors/movers

.changeset/poor-fishes-fry.md, crates/loro-ffi/src/doc.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/version.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
```rust
let doc_1 = LoroDoc::new();
doc_1.set_peer_id(1).unwrap();
doc_1.get_text("text").insert(0, "Hello world!").unwrap();
let doc_2 = LoroDoc::new();
doc_2.set_peer_id(2).unwrap();
doc_2.get_text("text").insert(0, "Hello world!").unwrap();
let blob11 = doc_1
.export(ExportMode::updates_in_range(vec![IdSpan::new(1, 0, 5)]))
.unwrap();
let blob12 = doc_1
.export(ExportMode::updates_in_range(vec![IdSpan::new(1, 5, 7)]))
.unwrap();
let blob13 = doc_1
.export(ExportMode::updates_in_range(vec![IdSpan::new(1, 6, 12)]))
.unwrap();
let blob21 = doc_2
.export(ExportMode::updates_in_range(vec![IdSpan::new(2, 0, 5)]))
.unwrap();
let blob22 = doc_2
.export(ExportMode::updates_in_range(vec![IdSpan::new(2, 5, 6)]))
.unwrap();
let blob23 = doc_2 …
```
=> feat: return import status in import_batch method

.changeset/friendly-geckos-juggle.md, crates/loro-internal/src/handler.rs, crates/loro/tests/loro_rust_test.rs
=> fix: getOrCreateContainer should not throw if value is null

.changeset/odd-beds-beg.md, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts
=> fix: panic when returned non-boolean value from text.iter(f) #577

Cargo.lock, crates/loro-ffi/Cargo.toml, crates/loro-ffi/src/undo.rs, crates/loro-internal/src/undo.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/undo.test.ts, crates/loro/tests/integration_test/undo_test.rs
Resolve #584 
cc: @raymonddaikon
=> feat: UndoManager's onPush now can access the change event

.changeset/rotten-penguins-relate.md, crates/loro-internal/src/loro.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/tests/loro_rust_test.rs
detaching should commit the pending ops
=> fix: panic when detach then attach

.changeset/old-snails-sell.md, crates/loro-internal/src/state.rs, crates/loro-wasm/src/lib.rs, crates/loro/src/lib.rs, crates/loro/tests/loro_rust_test.rs
Resolve https://github.com/loro-dev/loro-swift/issues/4
=> feat: make get_by_path work for tree

.changeset/chatty-experts-clean.md, crates/loro-internal/src/loro.rs, crates/loro/tests/loro_rust_test.rs
=> fix: should commit before travel_change_ancestors

.changeset/thin-actors-clean.md, .vscode/settings.json, crates/loro-internal/src/loro.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/tests/loro_rust_test.rs
From discussion on [Discord](https://discord.com/channels/1069799218614640721/1336346607742095471/1336727229878767797).
=> fix: should be able to call subscription after diffing

crates/kv-store/src/sstable.rs, crates/loro-internal/src/handler.rs, crates/loro-internal/src/utils/utf16.rs, crates/loro-wasm/tests/basic.test.ts
=> fix: mark err on detached LoroText

.changeset/twenty-rockets-fetch.md, crates/loro-internal/src/container/richtext/richtext_state.rs, crates/loro-internal/src/handler.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/__snapshots__/basic.test.ts.snap, crates/loro-wasm/tests/basic.test.ts, crates/loro/tests/loro_rust_test.rs
=> fix: detached loro text issues

.changeset/shiny-eggs-brake.md, crates/loro-ffi/src/config.rs, crates/loro-ffi/src/doc.rs, crates/loro-internal/src/container/richtext/config.rs, crates/loro-internal/src/loro.rs, crates/loro-wasm/src/lib.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro/src/lib.rs
=> feat: set default config for text style

crates/loro-internal/src/handler.rs, crates/loro/tests/loro_rust_test.rs
=> fix: apply multiple styles via text delta at the end "\n" char

.changeset/witty-dodos-learn.md, crates/loro-internal/src/handler/tree.rs, crates/loro/tests/loro_rust_test.rs
=> fix: panic when calling get_deep_value with an empty tree

.changeset/big-points-travel.md, crates/loro-internal/src/encoding.rs, crates/loro-internal/src/encoding/fast_snapshot.rs, crates/loro-internal/src/encoding/outdated_encode_reordered.rs, crates/loro-internal/src/loro.rs, crates/loro-internal/src/state.rs, crates/loro-internal/tests/test.rs
Fix: https://github.com/loro-dev/loro-swift/issues/20
=> fix: snapshot origin event

.changeset/itchy-dryers-cheer.md, Cargo.lock, crates/loro-wasm/src/convert.rs, crates/loro-wasm/tests/basic.test.ts, crates/loro-wasm/tests/json.test.ts
use null when export json update with undefined value
=> fix: export json update with undefined
